### PR TITLE
Re-render, R3.5, update recipe, update maintainers

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jdblischak** [comment]
@dbast You've been updating a lot of these recipes recently. What has been your strategy for responding to the linter's recommendation?

> Using toolchain directly in this manner is deprecated. Consider using the compilers outlined here.

**Comment by dbast** [comment]
@jdblischak Good question. I read the link the linter is writing, but it is not 100% clear to me.

I re-rendered all the feedstocks I touch and also compared the files with "conda skeleton cran $package" to carefully select updates.

Should I follow the skeleton builder, which suggests "{{native}}toolchain  # [win]", or revert that back to {{ compiler('m2w64_c') }}  # [win] + {{ compiler('m2w64_cxx') }}  # [win], which the linter likes more? Isn't "{{native}}toolchain  # [win]" also well defined via line 4 "{% set native = 'm2w64-' if win else '' %}"?

What do you suggests? 

Thanks

**Comment by jdblischak** [comment]
> I read the link the linter is writing, but it is not 100% clear to me.

Same here. I find it quite opaque.

> Should I follow the skeleton builder, which suggests "{{native}}toolchain # [win]", or revert that back to {{ compiler('m2w64_c') }} # [win] + {{ compiler('m2w64_cxx') }} # [win], which the linter likes more? Isn't "{{native}}toolchain # [win]" also well defined via line 4 "{% set native = 'm2w64-' if win else '' %}"?

I don't know. I tried following the linter's advice in https://github.com/conda-forge/r-markdown-feedstock/pull/3, but then that broke the Windows build. I don't know what I could have done wrong since the linter approved the recipe.

**Comment by dbast** [comment]
Ah, right, I remember now. I also had win-64 build failures in the past with other PRs, if I did not change the meta.yaml.

Seems like the the cause of this is, that the re-render removes the file .ci_support/win_.yaml, where "m2w64_c_compiler:\n - m2w64-toolchain" is defined and thus {{ compiler('m2w64_c') }}  # [win] will not work anymore. With the new re-render added .ci_support/win_r_base3.*.*target_platformwin-64.yaml it seems to be mandatory to use {{native}}toolchain        # [win].

Seems like we can ignore the linter message.

A look into the bot code also leads to the following linting code https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L323 which was added by @mariusvniekerk via https://github.com/conda-forge/conda-smithy/commit/72c02b4f9820458dbdc58a13139df08539e2216c . Maybe he has some advice here? Thanks!

**Comment by dbast** [comment]
@bgruening Do you have an idea here? supposed to be merge ready, see discussion. Thanks!

**Comment by cbrueffer** [comment]
Personally, I've been ignoring it so far. Not sure what the right course of action is.

**Comment by bgruening** [comment]
The problem is that r-base is not yet rebuilt with the new compilers. This will happen as soon as the rebuild-bot reaches r-base in the DAG. At this point, we need to change the compiler syntax as well - afaik.

**Comment by jdblischak** [comment]
Thanks everyone for the explanation! I'll ignore the linter's message about compilers for now.

**Pull request merged**
